Refact register knot
vitbaq/chirpstack-application-server pull request #12
Opened 2022-07-19 18:29 UTC by luisfelipemisi

- devEUI is used only to map the device in the integration context, then is generated a new KNoT id for this device and a token is requested to KNoT Cloud.
- Save the device context on a Volume Docker

2022-07-20 23:00 UTC, janael-pinheiro requested changes
Very good code.

2022-07-20 23:00 UTC, janael-pinheiro commented on internal/integration/knot/knot_protocol.go
>  //Teste Device
Teste -> Test

2022-07-20 23:00 UTC, janael-pinheiro commented on internal/integration/knot/knot_protocol.go
> +	if ok := checkFile("/etc/knot/deviceContex.yaml"); ok {
What do you think of assigning the filepath to a constant?

2022-07-20 23:00 UTC, janael-pinheiro commented on internal/integration/knot/knot_protocol.go
> +		if data.Schema.ValueType < 1 || data.Schema.ValueType > 5 {
What do you think about moving this condition to a function that takes the data.schema.ValueType and returns a boolean? For example, 
func isInvalidValueType(valueType int) bool {
   return valueType < 1 || valueType > 5
}

Also, consider assigning the values 1 and 5 to constants.

2022-07-20 23:00 UTC, janael-pinheiro commented on internal/integration/knot/knot_protocol.go
> +		if (device.State == values.KNoTNew && curDevice.State == values.KNoTWaitReg) ||
Please extract this condition to a function with a name that describes what is being checked and returns a boolean.

2022-07-27 17:54 UTC, rtorresmatheus commented on internal/integration/knot/knot_protocol.go
> +		p.writeDeviceFile("/etc/knot/deviceContex.yaml")
Same idea Janael said before. Can this be constant?

2022-07-27 18:11 UTC, rtorresmatheus commented on internal/integration/knot/knot_protocol.go
> +	err = os.WriteFile(pathFile, data, 0644)
What is the 0644 means? Can this be constant?

2022-08-05 17:41 UTC, merged